version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crawlerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    depends_on:
      - kafka

  scheduler:
    build: ./scheduler
    container_name: scheduler
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - postgres

  crawler:
    build: ./crawler
    container_name: crawler
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./html:/app/html  # ⬅ Mount host ./html to container /app/html

  parser:
    build: ./parser
    container_name: parser
    ports:
      - "8083:8080"
    depends_on:
      - kafka
    volumes:
      - ./html:/app/html  # ⬅ Same volume mount here
